//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test2Entities : DbContext
    {
        public Test2Entities()
            : base("name=Test2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<day> day { get; set; }
        public virtual DbSet<professor> professor { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_class> user_class { get; set; }
    }
}
