//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_class
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public byte id_class { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual user user { get; set; }
    }
}
